version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: wh1t34ox
      POSTGRES_USER: postgres
      POSTGRES_DB: journal
      PGDATA: /var/lib/postgresql/data/pgdata
      # POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      -  /var/lib/postgresql/data/postgresql:/var/lib/postgresql/datat
